const RESET_GAME = 'RESET_GAME';
const MATCH_START = 'MATCH_START';
const MATCH_END = 'MATCH_END';

const ROUND_START = 'ROUND_START';
const ROUND_COMMIT = 'ROUND_COMMIT';
const ROUND_UPDATE = 'ROUND_UPDATE';

const SWITCH_CARD = 'SWITCH_CARD';
const SELECT_CARD = 'SELECT_CARD';
const DISABLE_BOARD = 'DISABLE_BOARD';

export default {
   ROUND_UPDATE,
   ROUND_COMMIT,
   ROUND_START,
   SELECT_CARD,
   DISABLE_BOARD,
   SWITCH_CARD,
   MATCH_START,
   MATCH_END,
   RESET_GAME,
};
