const MAKE_MOVE = 'MAKE_MOVE';
const MATCH_START = 'MATCH_START';
const MATCH_RESET = 'MATCH_RESET';
const CHOOSE_CARD = 'CHOOSE_CARD';
const SWITCH_CARD = 'SWITCH_CARD';

export default {
   SWITCH_CARD,
   CHOOSE_CARD,
   MATCH_RESET,
   MATCH_START,
   MAKE_MOVE,
};
